### ISSUE TITLE
Can't add torrent

### ISSUE THREAD

**Issue by sscobici** [Feverqwe/uTiny_2#2]
I have Firefox 38.0.5 and uTorrent easy client 2.4.9.1.

I successfully configured webui access and can see torrents if I click on addon icon.

When I tried to add torrent from http://rutracker.org using context menu->Add in uTorrent I receive Can't add torrent.

**Comment by Feverqwe** [comment]
Hi! Rutracket block links without retracker referrer. I can't fix it.
